// Script assets have changed for v2.3.0 see
// https://help.yoyogames.com/hc/en-us/articles/360005277377 for more information
function Window_Captions(){
	
	WindowCaption[0] = "Not even a Prototype yet!"; //Default Caption.
	WindowCaption[1] = "Now in GitHub!";
	WindowCaption[2] = "Whew, that took awhile, at least now it's properly imported to GMS2_2.3";
	WindowCaption[3] = "Support us on Patreon!";
	WindowCaption[4] = "Window Captions, now with scripts!";
	WindowCaption[5] = "What's up with Window Captions?";
	WindowCaption[6] = "Window Captions will probably be important";
	WindowCaption[7] = "Red is the best color!"; //Submission by Tem.
	WindowCaption[8] = "This game is like love, don't break it too fast!"; //Submission by Bolt.
	WindowCaption[9] = "BLUB WAS HERE"; //Submission by Blub.
	WindowCaption[10] = "Dying is Gay!";
	WindowCaption[11] = "Cooler than Ice";
	WindowCaption[12] = "[INSERT MAPLE QUOTE HERE]";
	WindowCaption[13] = ". . .";
	WindowCaption[14] = "Gee, GitHub and GMS2!";
	WindowCaption[15] = "Pffft! Imagine living."; //Submission by Mystic
	WindowCaption[16] = "Haha! Existance is boring";
	WindowCaption[17] = "The Knocked off Knock-off";
	WindowCaption[18] = "Darkia stole all the knives, Good luck!"; //Submission by Darkia
	WindowCaption[19] = "There is no time, your sword is enough"; //Submission by Zenogias
	WindowCaption[20] = "Believe in the future you choose";
	WindowCaption[21] = "There is no spoon";
	WindowCaption[22] = "Vibe check!";
	WindowCaption[23] = "Cheeseburjer"; //Submission by Red
	WindowCaption[24] = "Maple: the Game | Charismancy and Seductionesis";
	WindowCaption[25] = "You think you're safe as you type this caption? I work in mysterious ways- I work behind your knowledge.";
	WindowCaption[26] = "Now with Music!";
	WindowCaption[27] = "Thank you, Tem. Very cool!";
	WindowCaption[28] = "Thank you, CalculatinGenius. Very cool!";
	WindowCaption[29] = "The Inventory Theme is creepy";
	WindowCaption[30] = "8 is the coolest number!";
	WindowCaption[31] = "32";
	WindowCaption[32] = "Blue is not Straight"; //Submission by E.
	WindowCaption[33] = "Shhhhhh! you're an Imposter";
	WindowCaption[34] = "R.I.P. Charles Calvin";
	WindowCaption[35] = "You are the CHAMPION";
	WindowCaption[36] = "Here are your Apex Champions";
	WindowCaption[37] = "Avi is cool!";
	WindowCaption[38] = "Not to be racist.. BUT";
	WindowCaption[39] = "Unpopular opinion, but Annie x Lily is better";
	WindowCaption[40] = "E";
	WindowCaption[41] = "F";
	WindowCaption[42] = "Walolo";
	WindowCaption[43] = "Narwini";
	WindowCaption[44] = "Erectus";
	WindowCaption[45] = "Also try Enchant!";
	WindowCaption[46] = "You leveled up! Your last message was 'Peanuts'"; //Submission by E.
	WindowCaption[47] = "90% Bug Free!"; //Submission by Blue
	WindowCaption[48] = "May or May not be 90% bug free";
	WindowCaption[49] = "Something about Noodles"; //Submission by Slushie
	WindowCaption[50] = "Getting a new Hard Drive!";
	WindowCaption[51] = "Getting the game into a different disk.. please don't mess up on me.";
	WindowCaption[52] = "I AM ERROR";
	WindowCaption[53] = "Oh my gosh, what will be in the caption?";
}